sudo: required
services:
  - docker


before_install:
  - docker build -t deirdrerodgers/docker-react -f Dockerfile.dev .
  
script:
  - docker run deirdrerodgers/docker-react npm run test -- --coverage  
  
